spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver

  main:
    banner-mode: off


logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
    springframework:
      security: TRACE

app:
  admin:
    email: ${adminEmail}
    username: ${adminUsername}
    password: ${adminPassword}

  jwt:
    secret: ${jwtSecret}
    expiration: ${jwtExpiration}


#server:
#  servlet:
#    context-path: /api

springdoc:
  enable-native-support: true
  swagger-ui:
    path: /swagger-ui
